name: Test
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  ci:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, ubuntu-20.04, windows-2019]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 11
      - name: Install Node Packages
        run: npm install
      - name: Run Unit Tests
        run: npm test
      - name: Run E2E Tests on Windows & MacOS
        run: npm run e2eTest
        if: runner.os != 'Linux'
        shell: bash
      - name: Run E2E Tests on Linux
        run: xvfb-run -a npm run e2eTest
        if: runner.os == 'Linux'